services:
  7days-server:
    image: 7days-server:latest
    container_name: 7days-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./days7-server
      dockerfile: Dockerfile
    ports:
      - "26900:26900"
      - "26901:26901"
      - "26902:26902"
      - "26903:26903"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
      - "26903:26903/udp"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - my_7days_server:/gameserver
    networks:
      - sv-network
  ftp-server:
    image: ftp-server:latest
    container_name: ftp-server
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    ports:
      - "20:20"
      - "21:21"
      - "40000-40024:40000-40024"
    volumes:
      - my_7days_server:/gameserver
    networks:
      - sv-network

volumes:
  my_7days_server:

networks:
  sv-network:
    driver: bridge